### ISSUE TITLE
need idea how to get rid of pattern

### ISSUE THREAD

**Issue by jschmied** [quatrope/astroalign#104]
The indy-allsky project uses this library to stack pictures of allsky cameras. It works partially since stacked images show more and fainter details. Some users complain about pattern in the picture. Any idea for tuning the stacking?

![ccd1_20241126_185941](https://github.com/user-attachments/assets/cd4f24a2-aa60-441a-ac48-4987945deeff)

This are 5x30 sec

**Comment by jschmied** [comment]
I guess, thats not alignment problem but a problem adding the pictures. Please close the issue.

**Comment by martinberoiz** [comment]
yes, that's probably an artifact of the CCD.
