### ISSUE TITLE
Feature request/discussion - additional RANSAC algorithm support

### ISSUE THREAD

**Issue by 84danie** [quatrope/astroalign#47]
I know that the docs + paper explain that astroalign becomes way more sensitive to outliers and may not work for smaller sets or require special care; have/would you consider adding support for other RANSAC algorithms? There's some variants that may combat this issue, such as [Optimal RANSAC](https://pdfs.semanticscholar.org/e925/0b95ecba159672e01d63f674d051f333b162.pdf), which is described as being able to handle situations when the inlier ratio is as little as 4%. 

I ask because for my use case at NASA JPL, the images being registered have very few stars that can be detected (~3-5, with 10-20 predicted), and I was curious if this idea had already been explored or not.

**Comment by martinberoiz** [comment]
@84danie by the way, do you know of any python implementation of Optimal RANSAC?

**Comment by 84danie** [comment]
I definitely think it would be worth adding additional support, or at least making it possible to plug in your own implementation. You might not even need adapter pattern - a simple way could be just putting the core functionality of the `find_transform` function into a class and placing the ransac code into a method of that class. Then users can just override that method with their own implementation and use the class directly instead of calling `find_transform`. An even simpler approach is just adding a functional parameter to the `find_transform`  function that allows users to pass their own RANSAC function (this could also be used to specify the specific ransac algorithm, if you end up supporting more in-house).

I tried playing around with `MAX_CONTROL_POINTS` - it didn't seem to have much of an effect. What did end up helping a lot (went from 30% registered to 88%) was effectively "pre-pruning" the initial lists of points of outliers. So I think this is further motivation for trying out different RANSAC algorithms designed for smaller inlier ratios.

Unfortunately, I don't know of any existing python implementations of Optimal RANSAC - you'd most likely have to implement it yourself based on the pseudocode.

**Comment by martinberoiz** [comment]
Version 2.4 implements a more "deterministic" (but still stochastic) ransac.
