### ISSUE TITLE
issue aligning astrophotography images

### ISSUE THREAD

**Issue by martinberoiz** [quatrope/astroalign#54]
> I'm seeing this problem too. Astroalign worked remarkably well when I was using it on crappy .cr2 images from an old Rebel, but now I have a Sony Alpha with a much more sensitive sensor, and when I try astroalign it always fails with MaxIterError. I'll attach a couple of sample images. _find_sources() on the two arrays I'm trying to align returns shapes (3860, 2) and (3990, 2) if I use raw .arw, or (10719, 2) and (11023, 2) for JPG. Github won't let me attach the raw files so here are two JPGs (not great astro images, just something I'm using to test aligning).

![dsc00938](https://user-images.githubusercontent.com/1451863/92413528-c75f4580-f10d-11ea-8e77-590f6d0f360a.jpg)

![dsc00937](https://user-images.githubusercontent.com/1451863/92413492-9ed74b80-f10d-11ea-8716-22dd12cfb9df.jpg)

_Originally posted by @akkana in https://github.com/toros-astro/astroalign/issues/39#issuecomment-688484363_

**Comment by akkana** [comment]
I'm using just the green channel to align. At least that's what my intent is -- no guarantees that my code is right. :-) I'm very new to this. But the same code worked on .cr2 images from the Canon. Here's the code I'm using: [starstack.py](https://github.com/akkana/scripts/blob/master/starstack.py#L278)
register() checks for rgb and calls singlelayer() which returns img[:, :, 1].

**Comment by martinberoiz** [comment]
Hello Akkana,

I made a test with the images provided and it seems that the alignment is working now with version 2.4.

<img width="547" alt="Screen Shot 2021-03-25 at 4 14 00 PM" src="https://user-images.githubusercontent.com/6099283/112544571-253f3c00-8d85-11eb-84c9-11240e4b07b2.png">

If you still have problems, please feel free to open a new issue, I will go ahead and close this now.
