### ISSUE TITLE
repeated find_transform on same sets of (x,y) tuples give different results

### ISSUE THREAD

**Issue by msz59** [quatrope/astroalign#64]
I am trying `astroalign.find_transform` to match two lists of X,Y - star detections in two FITS images of the same region. To my great surprise, when I ran it second time, I got different results. Third time - yet another. Does it make any sense or I am doing something wrong here?
I am really puzzled.
```
>>> xy1t
[(28.78, 271.52), (85.44, 257.88), ... (1976.47, 148.31), (1996.3, 150.18)]
>>> xy2t
[(18.0, 94.06), (20.16, 267.55), ...  (2020.51, 122.79)]
>>> len(xy1t)
47
>>> len(xy2t)
65
>>> transfa, (list1a, list2a) = aa.find_transform(xy1t, xy2t)
>>> list1a
array([[ 881.2 ,  280.04],
       [ 958.07,  220.58],
       [ 658.43,  276.06],
       [1336.93,  228.51],
       [1029.09,   75.06],
       [1037.3 ,  211.96],
       [ 657.58,  180.65],
       [1339.71,  126.23],
       [ 582.18,  226.42],
       [1222.58,  194.06],
       [1197.93,   53.49],
       [1159.18,   44.35],
       [1088.24,   43.85],
       [1081.26,   71.93],
       [1151.12,  193.77]])
>>> transfa
<SimilarityTransform(matrix=
    [[ 1.00236715e+00,  2.10730110e-02,  3.42981642e+01],
     [-2.10730110e-02,  1.00236715e+00,  1.49585410e+01],
     [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]) at 0x7fb709aa5310>
>>> transfb, (list1b, list2b) = aa.find_transform(xy1t, xy2t)
>>> list1b
array([[ 881.2 ,  280.04],
       [ 958.07,  220.58],
       [1029.09,   75.06],
       [1037.3 ,  211.96],
       [1197.93,   53.49],
       [1159.18,   44.35],
       [1088.24,   43.85],
       [1081.26,   71.93],
       [1151.12,  193.77]])
>>> transfb
<SimilarityTransform(matrix=
    [[ 9.99061527e-01,  2.11305180e-02,  3.78746167e+01],
     [-2.11305180e-02,  9.99061527e-01,  1.53563603e+01],
     [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]) at 0x7fb709aa5400>
```

**Comment by msz59** [comment]
Some auto-randomization of the sequence of points/triangles processed?

**Comment by martinberoiz** [comment]
Hi,

That’s right, astroalign uses a RANSAC algorithm that it’s stochastic in nature. The results may change from run to run but they should not change too much.

Apparently there are “deterministic” ransac algorithms out there but I haven’t had the chance to implement those.

**Comment by msz59** [comment]
My test was done on objects detected on circa 300x2048 frames. As it seems, the find_transform() identifies objects in smaller regions (different in every run) of these frames. That shows that the transformation (linear) used internally is insufficient. It would be probably worth adding "order" as an additional parameter.

**Comment by martinberoiz** [comment]
The correspondence of those few stars is provided just as a reference. If you want to find the correspondence of a different larger set, or predefined objects, first estimate the transformation as you did, and then apply it to the desired objects.

Here is a [relevant explanation](https://astroalign.readthedocs.io/en/latest/tutorial.html#applying-a-transformation-to-a-set-of-points).

I will go ahead and close this issue but feel free to post a message if you still have questions.

**Comment by msz59** [comment]
The *correspondence* between stars are probably determined by applying the transformation and searching in a predefined radius of (x,y) in the other set of objects. I guess that the (different) results of repeated runs of `find_transform` show that depending of randomly selected first points/pairs/triangles one gets slightly differing transformations which do not work well far from the region where they were calculated, thus not finding the *correspondences* there.
I think that introducing (possibly as an optional parameter) higher-order transformations would fix that problem.
