### ISSUE TITLE
Implement "downsampling"

### ISSUE THREAD

**Issue by ysBach** [quatrope/astroalign#69]
I've just encountered ~10 4K images to combine.
I am using Macbook Pro 15" (MBP 15" [2018, macOS 11.4, i7-8850H (2.6 GHz; 6-core), RAM 16 GB (2400MHz DDR4), Radeon Pro 560X (4GB)]), and it takes ~ 3-4 seconds to register an image.
I tested with 4x4 binning to the data, and it was << 1 sec order (as expected).

I guess something like ``bin_factors=(2, 2)`` can be implemented to ``aa.register``...

(of course I can do this by myself using (1) bin each image, (2) find transform, (3) slightly modify the transform matrix, (4) apply the updated transform. But it is a bit too much of coding...)

**Comment by martinberoiz** [comment]
Hi @ysBach, that is a good suggestion.

I have a few other features that are in line to imlement and I will add this one to the list. I will probably plan a sprint soon to code these additions.
