### ISSUE TITLE
Use numpy.random.Generator.shuffle instead of np.random.shuffle

### ISSUE THREAD

**Issue by dholzber** [quatrope/astroalign#82]
1. The current RANSAC implementation uses `numpy.random.shuffle`. This should be changed to instead use the updated, recommended, random Generator API ([noted in the numpy docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html)). 
2. In addition to 1, add a random_state input parameter that can be passed down to `ransac` to the public API.

Note: the [latest version of skimage's ransac function](https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=ransac#skimage.measure.ransac) referenced in issue #76 accomplishes 1 and 2.

**Comment by martinberoiz** [comment]
Noted

**Comment by martinberoiz** [comment]
implemented in 2.5.0
