### ISSUE TITLE
astroalign.MaxIterError: List of matching triangles exhausted before an acceptable transformation was found

### ISSUE THREAD

**Issue by timegate** [quatrope/astroalign#91]
I tried to align below 2 images, but I get an error "astroalign.MaxIterError: List of matching triangles exhausted before an acceptable transformation was found."
source
![SavedView](https://user-images.githubusercontent.com/16134605/232289841-be5fe917-e888-49cf-9f2e-a859faa254c5.png)
target
![ea1](https://user-images.githubusercontent.com/16134605/232289839-8d6fa3f6-c66c-41c4-b364-5df676bcf127.jpg)

I thought it was because it has too much candidates, so I tried a source image with fewer stars
source2
![stellarium-003 (2)](https://user-images.githubusercontent.com/16134605/232290005-ce77fc11-6cbd-4dfb-8c60-20d6e4359d66.png)

But the same error happened again (changing source <-> target also showed the same error).

Could you please explain why it doesn't work? or is there any workaround?

**Comment by martinberoiz** [comment]
I see. This problem is most likely due to all the extra space in the target image that has no correspondence with either of the sources --i.e. the field of view of both is quite different.

I think masking the region of interest (masking out the extra space) could be a solution. This is related to #90. I'll try implementing this ASAP and we can try again with masking.

**Comment by timegate** [comment]
Wow, thanks for fast and kind reply. I got the point exactly. Thanks so much.

Umm.. I hope that we find a way to align 2 images regardless of fov. I found that astrometry finds WCS well regardless of fov, so maybe it would be nice to leverage the two WCSs found so that the aligning works regardless of fov.

**Comment by timegate** [comment]
Maybe 1. Astrometry -> 2. Astroalign with known stars (https://astroalign.quatrope.org/en/latest/tutorial.html#if-you-know-the-star-to-star-correspondence) could be one way. How do you think about this way?

**Comment by martinberoiz** [comment]
Sure, if you want to involve WCS, I would recommend solving it with astrometry.net and then use something like [reproject](https://github.com/astropy/reproject) to do the mapping.
