### ISSUE TITLE
Make SEP optional

### ISSUE THREAD

**Issue by juliotux** [quatrope/astroalign#99]
SEP is not being maintened and do not support newer Python and Numpy versions. There are forks pushing updates, like `sep-pjw` and `sdss-sep`, but with different names. This can break some environments.

Make `sep` an optional dependency with import checking when needed, or a conditional dependency as defined by [PEP 631](https://peps.python.org/pep-0631/) may solve the problem.

**Comment by martinberoiz** [comment]
Thanks Julio for pointing this issue out. I've been reading about making dependencies optional but it would be too much trouble allowing to swap sep by any arbitrary sep fork, so I pick sep-pjw which seems the fork that's more maintained and with richer features.

The new version 2.6.0 uses sep-pjw and drops supports for python 3.8. Let me know if you find any issues.
